FROM ubuntu:bionic

# Install prerequisities for Ansible
RUN apt-get update -y
RUN apt-get -y install python3.8 software-properties-common apt-get sshpass vim net-tools systemd git curl

# Install ansible
RUN apt-add-repository ppa:ansible/ansible \ 
    && apt update \ 
    && apt install ansible

# Over rides SSH Hosts Checking
RUN echo "host *" >> ~/.ssh/config &&\
    echo "StrictHostKeyChecking no" >> ~/.ssh/config

# Makes a directory for ansible playbooks
RUN mkdir -p /ansible/playbooks

# Makes the playbooks directory the working directory
WORKDIR /ansible/playbooks

# Sets environment variables
ENV ANSIBLE_GATHERING smart
ENV ANSIBLE_HOST_KEY_CHECKING False
ENV ANSIBLE_RETRY_FILES_ENABLED False
ENV ANSIBLE_ROLES_PATH /ansible/playbooks/roles
ENV ANSIBLE_SSH_PIPELINING True
ENV PATH /ansible/bin:$PATH

ENTRYPOINT["ansible-playbook"]
